import { Request, Response, Router } from 'express';

const router = Router();

router.get('/', (req: Request, res: Response) => {
  return res.json({
    data: [
      {
        id: 'srv_001',
        category: 'Coiffure',
        name: 'Brushing',
        description: 'Coiffage professionnel avec brushing 3D',
        price_from: 300,
        price_to: 600,
        currency: 'DZD',
        duration: '30 min',
        icon: 'hair-dryer',
        image: '/uploads/Hair-Styling.png',
      },
      {
        id: 'srv_002',
        category: 'Traitement Capillaire',
        name: 'Traitement à la Protéine',
        description: 'Traitement fortifiant des cheveux à base de protéine',
        price_from: 2500,
        currency: 'DZD',
        duration: '60 min',
        icon: 'flask',
        image: '/uploads/Protein-treatment.png',
      },
      {
        id: 'srv_003',
        category: 'Traitement Capillaire',
        name: 'Traitement à la Kératine',
        description: 'Traitement lissant à la kératine',
        price_from: 2500,
        currency: 'DZD',
        duration: '90 min',
        icon: 'flask',
        image: '/uploads/KeratinTreatment.png',
      },
      {
        id: 'srv_004',
        category: 'Soins du Visage',
        name: 'Soin du Visage',
        description: 'Soin profond et complet du visage',
        price_from: 1000,
        currency: 'DZD',
        duration: '45 min',
        icon: 'face',
        image: '/uploads/Facial-Care.png',
      },
      {
        id: 'srv_005',
        category: 'Soins du Visage',
        name: 'Nettoyage de la Peau',
        description: 'Nettoyage professionnel de la peau',
        price_from: 2000,
        currency: 'DZD',
        duration: '50 min',
        icon: 'water',
        image: '/uploads/skin-cleaning.png',
      },
      {
        id: 'srv_006',
        category: 'Coloration Capillaire',
        name: 'Coloration des Cheveux (Agiva)',
        description: 'Coloration des cheveux avec les produits Agiva',
        price_from: 800,
        currency: 'DZD',
        duration: '40 min',
        icon: 'color-palette',
        image: '/uploads/Hair-Coloring.png',
      },
      {
        id: 'srv_007',
        category: 'Coloration Capillaire',
        name: 'Coloration Toppik',
        description: 'Coloration des cheveux avec fibres Toppik',
        price_from: 800,
        currency: 'DZD',
        duration: '30 min',
        icon: 'color-palette',
        image: '/uploads/Hair-Coloring.png',
      },
      {
        id: 'srv_008',
        category: 'Soins Capillaires',
        name: 'Shampooing Colorant',
        description: 'Service de shampooing colorant',
        price_from: 500,
        currency: 'DZD',
        duration: '20 min',
        icon: 'bottle',
        image: '/uploads/Shampoo-Coloring.png',
      },

      // --- Coupes ---

      {
        id: 'srv_009',
        category: 'Coupe de Cheveux',
        name: 'Coupe Homme',
        description: 'Coupe classique pour homme',
        price_from: 500,
        currency: 'DZD',
        duration: '25 min',
        icon: 'cut',
        image: '/uploads/classic-haircut.png',
      },
      {
        id: 'srv_010',
        category: 'Coupe de Cheveux',
        name: 'Coupe Enfant',
        description: 'Coupe de cheveux pour enfants',
        price_from: 300,
        currency: 'DZD',
        duration: '20 min',
        icon: 'cut',
        image: '/uploads/kids-haircut.png',
      },
      {
        id: 'srv_011',
        category: 'Coupe de Cheveux',
        name: 'Contour des Oreilles',
        description: 'Contour des cheveux autour des oreilles',
        price_from: 200,
        currency: 'DZD',
        duration: '10 min',
        icon: 'scissors',
        image: '/uploads/EarContour.png',
      },
      {
        id: 'srv_012',
        category: 'Coupe & Barbe',
        name: 'Contour + Barbe',
        description: 'Contour des oreilles avec taille de la barbe',
        price_from: 400,
        currency: 'DZD',
        duration: '20 min',
        icon: 'beard',
        image: '/uploads/HaircutBeard.png',
      },
      {
        id: 'srv_013',
        category: 'VIP',
        name: 'Coupe VIP',
        description: 'Expérience premium de coupe VIP',
        price_from: 1000,
        currency: 'DZD',
        duration: '45 min',
        icon: 'crown',
        is_vip: true,
        image: '/uploads/vip-banner.jpg',
      },
      {
        id: 'srv_014',
        category: 'Service à Domicile',
        name: 'Coupe à Domicile',
        description: 'Coupe de cheveux au domicile du client',
        price_from: 2000,
        currency: 'DZD',
        duration: '60 min',
        icon: 'home',
        image: '/uploads/HomeHaircut.png',
      },
    ],
  });
});

export default router;
