import { Request, Response, Router } from 'express';

const router = Router();

router.get('/', (req: Request, res: Response) => {
  return res.json({
    data: [
      {
        id: 'srv_001',
        category: 'Hair Styling',
        name: 'Brushing',
        description: 'Professional 3D brushing hairstyle',
        price_from: 300,
        price_to: 600,
        currency: 'DZD',
        duration: '30 min',
        icon: 'hair-dryer',
        image: '/uploads/Hair-Styling.png',
      },
      {
        id: 'srv_002',
        category: 'Hair Treatment',
        name: 'Protein Treatment',
        description: 'Hair protein strengthening treatment',
        price_from: 2500,
        currency: 'DZD',
        duration: '60 min',
        icon: 'flask',
        image: '/uploads/Protein-treatment.png',
      },
      {
        id: 'srv_003',
        category: 'Hair Treatment',
        name: 'Keratin Treatment',
        description: 'Keratin hair smoothing treatment',
        price_from: 2500,
        currency: 'DZD',
        duration: '90 min',
        icon: 'flask',
        image: '/uploads/KeratinTreatment.png',
      },
      {
        id: 'srv_004',
        category: 'Skin Care',
        name: 'Facial Care',
        description: 'Deep facial skin care',
        price_from: 1000,
        currency: 'DZD',
        duration: '45 min',
        icon: 'face',
        image: '/uploads/Facial-Care.png',
      },
      {
        id: 'srv_005',
        category: 'Skin Care',
        name: 'Skin Cleaning',
        description: 'Professional skin cleansing',
        price_from: 2000,
        currency: 'DZD',
        duration: '50 min',
        icon: 'water',
        image: '/uploads/skin-cleaning.png',
      },
      {
        id: 'srv_006',
        category: 'Hair Coloring',
        name: 'Hair Coloring (Agiva)',
        description: 'Hair dye using Agiva products',
        price_from: 800,
        currency: 'DZD',
        duration: '40 min',
        icon: 'color-palette',
        image: '/uploads/Hair-Coloring.png',
      },
      {
        id: 'srv_007',
        category: 'Hair Coloring',
        name: 'Toppik Hair Coloring',
        description: 'Hair coloring with Toppik fibers',
        price_from: 800,
        currency: 'DZD',
        duration: '30 min',
        icon: 'color-palette',
        image: '/uploads/Hair-Coloring.png',
      },
      {
        id: 'srv_008',
        category: 'Hair Care',
        name: 'Shampoo Coloring',
        description: 'Coloring shampoo service',
        price_from: 500,
        currency: 'DZD',
        duration: '20 min',
        icon: 'bottle',
        image: '/uploads/Shampoo-Coloring.png',
      },

      // --- Haircuts ---

      {
        id: 'srv_009',
        category: 'Haircut',
        name: 'Men Haircut',
        description: 'Classic men haircut',
        price_from: 500,
        currency: 'DZD',
        duration: '25 min',
        icon: 'cut',
        image: '/uploads/classic-haircut.png',
      },
      {
        id: 'srv_010',
        category: 'Haircut',
        name: 'Kids Haircut',
        description: 'Haircut for children',
        price_from: 300,
        currency: 'DZD',
        duration: '20 min',
        icon: 'cut',
        image: '/uploads/kids-haircut.png',
      },
      {
        id: 'srv_011',
        category: 'Haircut',
        name: 'Ear Contour',
        description: 'Hair contour around ears',
        price_from: 200,
        currency: 'DZD',
        duration: '10 min',
        icon: 'scissors',
        image: '/uploads/EarContour.png',
      },
      {
        id: 'srv_012',
        category: 'Haircut & Beard',
        name: 'Ear Contour + Beard',
        description: 'Ear contour with beard trimming',
        price_from: 400,
        currency: 'DZD',
        duration: '20 min',
        icon: 'beard',
        image: '/uploads/HaircutBeard.png',
      },
      {
        id: 'srv_013',
        category: 'VIP',
        name: 'VIP Haircut',
        description: 'Premium VIP haircut experience',
        price_from: 1000,
        currency: 'DZD',
        duration: '45 min',
        icon: 'crown',
        is_vip: true,
        image: '/uploads/vip-haircut.png',
      },
      {
        id: 'srv_014',
        category: 'Home Service',
        name: 'Home Haircut',
        description: 'Haircut at customer home',
        price_from: 2000,
        currency: 'DZD',
        duration: '60 min',
        icon: 'home',
        image: '/uploads/HomeHaircut.png',
      },
    ],
  });
});

export default router;
